name: Run app.py

on:
  push:
    paths:
      - 'app.py'
  workflow_dispatch:

jobs:
  run-app:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt || true  # Skip if no requirements.txt

    - name: Run app.py
      run: python app.py
